// All of the types (i.e. actions) that the app will do.
export const FORECAST_ERROR = 'FORECAST_ERROR';
export const GET_SHOW_FIVE_DAY_FORECAST_FLAG = 'GET_SHOW_FIVE_DAY_FORECAST_FLAG';
export const GET_USER_CLICKED_WEATHER_FORECAST_OBJECT = 'GET_USER_CLICKED_WEATHER_FORECAST_OBJECT';
export const GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST';
export const GET_WEATHER_FORECAST_LOCATION = 'GET_WEATHER_FORECAST_LOCATION_DATA';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const GET_SHOW_TEMP_IN_C = 'GET_SHOW_TEMP_IN_C'